# Generated by Django 6.0.3 on 2026-03-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0002_alter_car_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('naujas', 'Naujas'), ('vykdomas', 'Vykdomas'), ('baigtas', 'Baigtas'), ('atšauktas', 'Atšauktas')], default='naujas', max_length=20, verbose_name='Statusas'),
        ),
    ]
