# Generated by Django 6.0.3 on 2026-03-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0003_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(max_length=100, verbose_name='Gamintojas'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('naujas', 'Naujas'), ('vykdomas', 'Vykdomas'), ('baigtas', 'Baigtas'), ('atsauktas', 'Atšauktas')], default='naujas', max_length=20, verbose_name='Statusas'),
        ),
    ]
