# Generated by Django 6.0.3 on 2026-03-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0004_alter_car_make_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Kiekis'),
        ),
    ]
