# Generated by Django 6.0.3 on 2026-03-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0006_car_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderline',
            name='status',
            field=models.CharField(choices=[('laukiama', 'Laukiama'), ('vykdoma', 'Vykdoma'), ('baigta', 'Baigta')], default='laukiama', max_length=20, verbose_name='Paslaugos statusas'),
        ),
    ]
