# Generated by Django 6.0.3 on 2026-03-27 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0008_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date'], 'verbose_name': 'Užsakymas', 'verbose_name_plural': 'Užsakymai'},
        ),
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, verbose_name='Aprašymas'),
        ),
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, verbose_name='Aprašymas'),
        ),
        migrations.AddField(
            model_name='order',
            name='return_date',
            field=models.DateField(blank=True, null=True, verbose_name='Grąžinimo data'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Vartotojas'),
        ),
    ]
