# Generated by Django 6.0.3 on 2026-03-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0010_alter_order_options_remove_car_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
