# Generated by Django 6.0.3 on 2026-03-27 17:06

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0011_order_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Aprašymas'),
        ),
    ]
